### ISSUE TITLE
Do you accept PR's?

### ISSUE THREAD

**Issue by thetutlage** [file-icons/MFixx#1]
I want to integrate icon for my library http://edge.adonisjs.com/. Do you accept PR's?

**Comment by Alhadis** [comment]
What do you want to do, exactly?

**Comment by Alhadis** [comment]
As in, when you say "integrate", what are you referring to?

**Comment by thetutlage** [comment]
So this atom plugin https://github.com/file-icons/atom shows icons next to the file type/extension. It shows this by using a list of font icons from this repo. 

So I want to add an icon of mine to this repo, so that I can reference it within atom.

Makes sense? Happy to explain more

**Comment by Alhadis** [comment]
First of all, wrong repository and wrong font. The `file-icons` package bundles several icon-fonts... but there's only one that gets updated with new icons.

The correct repository is [`file-icons/source`](https://github.com/file-icons/source). Please file an issue with the icon added as an attachment.

**Comment by thetutlage** [comment]
Thanks 😄
