### ISSUE TITLE
Sorry how to use it ?

### ISSUE THREAD

**Issue by Esysteme** [file-icons/MFixx#2]
``@font-face {
  font-family: 'MFixx';
  src: url('../fonts/MFixx.eot'); /* IE9 Compat Modes */
  src: url('../fonts/MFixx.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/MFixx.woff') format('woff'), /* Modern Browsers */
       url('../fonts/MFixx.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('../fonts/MFixx.svg#svgFontName') format('svg'); /* Legacy iOS */
}``

then add

``
.geek
{
    font-family: "MFixx";
}
``

to finish 

``MariaDB <span class="geek">\F130</span>``

**Comment by Alhadis** [comment]
I'm sorry, I'm not really sure I know what you're saying...

What are you trying to do?

**Comment by Esysteme** [comment]
i trying to display icon of MySQL and MariaDB on website

**Comment by Esysteme** [comment]
i take the code from https://github.com/file-icons/MFixx/blob/master/charmap.md

i add this in css


```
.geek
{
    font-family: "MFixx";
    font-weight: normal;
    font-style: normal;

}
.mysql {content:"\f137";}
```


and this in html:

``MariaDB <span class="geek mysql">\F130</span>``

**Comment by Alhadis** [comment]
You're close. You just need to fix this part:

```html
MariaDB <span class="geek">\F130</span>
```

Change `\F130` so it becomes `&#xF130;` instead. The `\F130` notation is used in CSS, but not HTML.

**Comment by Esysteme** [comment]
this working really good thx you  (with `&#xF130;`)

**Comment by Alhadis** [comment]
Glad to hear it! 😉
